# Generated by Django 6.1.1 on 2026-10-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snaptrade_user_id', models.CharField(blank=True, max_length=100)),
                ('snaptrade_portfolio_id', models.CharField(blank=True, max_length=100)),
                ('snaptrade_user_secret', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('position_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_return', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cumilative_return', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=15)),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('total_trades', models.IntegerField()),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='performance_portfol_321b6f_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unrealized_pl_pct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.stock')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-current_value'],
                'unique_together': {('portfolio', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('filled_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filled_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('external_order_id', models.CharField(blank=True, max_length=100)),
                ('snaptrade_order_id', models.CharField(blank=True, max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.stock')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='trades_status_425b31_idx'), models.Index(fields=['created_at'], name='trades_created_5d2ae4_idx')],
            },
        ),
    ]
